name: Build and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install pdflatex
        run: sudo apt-get install -y texlive-latex-base   texlive-latex-extra

      - name: Compile latex
        run: cd doc && pdflatex 1chipML_manual.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: doc/1chipML_manual.tex
